route:
  group_by: ['k3s','HealtyServer']

  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

receivers:
- name: discord
  discord_configs:
    - webhook_url: '${URL}'

