apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
  labels:
    app: web-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.25
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gitops-service
spec:
  selector:
    app: web-nginx
  type: NodePort
  ports:
    - name: myjob
      port: 80
      targetPort: 80
      nodePort: 30085
