route:
  receiver: 'tim_sre_devops'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'tim_sre_devops'
  webhook_configs:
    - url: 'https://discordapp.com/api/webhooks/1509474245443457086/N3A21xor5cLv1P2ZNJXiG52Tazj23MKk2rQ6D_fWPVvZoiVmbPAMOdsbn_1JO__nUgFs'

